### ISSUE TITLE
Tor/Onion websites flagged as death.

### ISSUE THREAD

**Issue by Illegal-Services** [cadeyrn/bookmarks-organizer#178] opened 2022-03-13 10:41 UTC
Alright I do not have a way to check whenever a onion website is UP or Down / changed domain;
But currently Bookmarks Organizer says they are all down, can you do anything for it?
I suggest moving them in a category, kind of like debug mode of your app OR an easier solution would be to ignore those url from scanning.

**Comment by cadeyrn** [comment] 2022-03-13 10:55
I need an example to reproduce to say anything about it.

**Comment by Illegal-Services** [comment] 2022-03-13 11:16
![firefox_2022-03-13_12-15](https://user-images.githubusercontent.com/62464560/158056912-cb76389f-740e-4634-962b-2a4bdb198fe0.png)

Also it would be great feature because bookmarks ARE actually usable on for example Tor and Brave browsers

**Comment by Illegal-Services** [comment] 2022-03-13 11:17
Also it would be great feature because bookmarks ARE actually usable on for example Tor and Brave browsers.

**Comment by cadeyrn** [comment] 2022-03-13 14:55
Please provide the URL of an example that is legally allowed. I won't support illegal use cases.

**Comment by Illegal-Services** [comment] 2022-03-13 14:57
??? onion websites are only available trough Tor network

**Comment by cadeyrn** [comment] 2022-03-13 15:05
> ???

The screenshot in your previous comment clearly showed bookmarks of illegal services. And that's not acceptable at all.

**Comment by Illegal-Services** [comment] 2022-03-13 15:08
Well I've assumed once you've read it you could will delete it, and once you've replied I  would delete it anyways;
that is the reason I've edited it and written the line behind:
[#issuecomment-1066079477](https://github.com/cadeyrn/bookmarks-organizer/issues/178#issuecomment-1066079477)

**Comment by Illegal-Services** [comment] 2022-03-13 15:10
You asked me an example to reproduce, I don't understand what you mean so I just sent the unwanted behaviour in your app, thinking you didn't understood what I've meant in my issue here.

**Comment by cadeyrn** [comment] 2022-03-13 17:44
> Well I've assumed once you've read it you will delete it, and once you've replied I would've anyways delete it.

That's not the point. It's true that I don't want to have references to illegal services in my issues tracker but much more I do not want to support anti-social people who do illegal things because we honest people have to pay a price for all the ass-hole people who think they are above the law. So I am not interested in examples of illegal services even if the example get deleted afterwards.

> You asked me an example to reproduce, I don't understand what you mean so I just sent the unwanted behaviour in your app

To fix or to improve something I have to be able to reprodude the problem. Therefore I need a bookmark URL that can be used to see the problem and find a solution. But I am only interested in legal examples.

**Comment by Illegal-Services** [comment] 2022-03-13 17:53
> That's not the point. It's true that I don't want to have references to illegal services in my issues tracker but much more I do not want to support anti-social people who do illegal things because we honest people have to pay a price for all the ass-hole people who think they are above the law. So I am not interested in examples of illegal services even if the example get deleted afterwards.

I understand that posting illegal links in that repository was a mistake, and I apologize for that.

> To fix or to improve something I have to be able to reprodude the problem. Therefore I need a bookmark URL that can be used to see the problem and find a solution. But I am only interested in legal examples.

**FaceBook:**
https://facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion
**DuckDuckGo:**
https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/html/

**Comment by cadeyrn** [comment] 2023-01-08 22:05
It's a WONTFIX because it works if you use a browser that is able to open .onion domains. So if you use Firefox in it's default configuration it can't open these domains so these bookmarks are in fact broken. If you use the add-on in the Tor browser these domains can be opened and the Bookmarks Organizer doesn't mark these bookmarks as broken.

**Closed by cadeyrn** 2023-01-08 22:05 UTC
