### ISSUE TITLE
URLs falsely marked as "red"

### ISSUE THREAD

**Issue by rugk** [cadeyrn/bookmarks-organizer#4] opened 2017-05-20 14:25 UTC
Maybe they were requested too fast or the redirects were not recognized, but many – properly working – bookmarks were marked as non-existent (red) in my test.

**Comment by cadeyrn** [comment] 2017-05-20 16:34
If you execute the check more than 1x, are there always the same URLs marked as errors? If so can you tell me the URLs?

**Comment by rugk** [comment] 2017-05-21 15:13
I assume they are always the same. It seems it almost marks all bookmarks scanned with a red label. Maybe it overloads itself and then timeouts get too high or so. This is the only explanation I have.

E.g. https://cipherli.st/ & https://sslmate.com/certspotter/

**Comment by cadeyrn** [comment] 2017-05-27 06:21
Unfortunately I can't reproduce the issue, so the bookmark URLs are fine. Your explanation could be right if you have a lot of bookmarks. Do you have an idea to improve this case?

**Comment by ScottNAtlanta** [comment] 2017-06-02 03:30
I had this issue with the URL
https://www.paypal.com/us/home

**Comment by cadeyrn** [comment] 2017-06-04 12:29
I can't reproduce. Please let me know if you have clear steps to reproduce or any ideas to improve the reliability of the check.

**Closed by cadeyrn** 2017-06-04 12:29 UTC
Labels: bug, not reproducible
