### ISSUE TITLE
Tracking protection interfers with bookmark checks

### ISSUE THREAD

**Issue by freaktechnik** [cadeyrn/bookmarks-organizer#26] opened 2017-05-27 18:20 UTC
I have a bookmark to https://www.reddit.com/r/AskReddit/comments/uou6z/update_i_was_requested_to_compile_all_of_the/ in my other bookmarks.

When I check for broken bookmarks, this bookmark is listed as being broken. Well, what I assume as being broken, as it has a red dot next to it.

**Comment by cadeyrn** [comment] 2017-05-28 07:02
I cannot reproduce. Can you if you test again?

**Comment by freaktechnik** [comment] 2017-05-28 07:45
Yes, it is reliable for me.

Is there any way other than writing my own extension to find out the bookmark URL the extension gets for example? The URL I copied above comes from the edit field in the places manager.

**Comment by cadeyrn** [comment] 2017-05-28 07:58
Hm… the add-on has a debug output but it seems to be broken in the current version. :( I can repair the debug output and upload a new version to AMO.

**Comment by freaktechnik** [comment] 2017-05-28 08:46
Actually found out what is happening with about:debugging: The URL is blocked by tracking protection, which I have enabled globally in Nightly with the less restrictive list.

**Comment by freaktechnik** [comment] 2017-05-28 08:59
From https://bugzilla.mozilla.org/show_bug.cgi?id=1308640it seems that explicitly listing a site in the permissions would solve this... not really a nice way to deal with it for this extension. I wonder why TP would block a request to https://www.reddit.com though.

**Comment by freaktechnik** [comment] 2017-05-28 10:23
I wonder if loading pages in an iframe instead of via fetch would solve this, since Firefox would then properly load the page if possible? Not sure how well you can check the status of a website though. Maybe as fallback?

**Comment by cadeyrn** [comment] 2017-05-29 16:32
Thank you for your investigation! I can confirm that Reddit links don't work with tracking protection enabled.

**Comment by fmarier** [comment] 2017-06-02 23:54
@mixedpuppy, this seems like a similar problem to what you addressed in https://bugzilla.mozilla.org/show_bug.cgi?id=1308640.

In this case, the add-on (which checks bookmarks for dead links) checks URLs and can't distinguish between a genuine network error and Safe Browsing / Tracking Protection errors.

Here are some more test URLs:

- <https://developers.google.com/safe-browsing/v4/update-api> (Tracking Protection)
- <http://itisatrap.org/firefox/its-a-trap.html> (Safe Browsing)
- <http://itisatrap.org/firefox/its-an-attack.html> (Safe Browsing)

I wonder whether add-ons should be able to get a different error code when TP or SB blocks these reuqests?

**Comment by cadeyrn** [comment] 2018-02-25 08:38
working on it.

**Closed** 2018-02-25 08:55 UTC
Labels: enhancement
