### ISSUE TITLE
Bug: BO check waits for a few bookmarks forever - No timeout - No abort button

### ISSUE THREAD

**Issue by pstein** [cadeyrn/bookmarks-organizer#167] opened 2021-12-27 14:58 UTC
I have approx. 5200 bookmarks.
When I start to check them with BO then everything works well at the beginning.

After 20 minutes or so almost all bookmarks are checked except 2 of them.
The running thumbnail indicator in the mid still flashes.
Even after 1 hour it still flashes.

I cannot find an abort button.
Unfortunately BO seems not to have a internal timeout but tries to search forever.
I cannot even find out which bookmark is the critical BO waits for.

This makes BO almost unusable.

Does BO have a bookmark list size problem?

Can this be fixed in the next release?

Thank you

**Comment by cadeyrn** [comment] 2021-12-27 15:32
Bookmarks Organizer does have an internal timer for the bookmark check so I guess it counts somethings as bookmark that is not a bookmark and that doesn't get checked. Unfortunately I can't say anything without the ability to test it with the affected data. Can you share an export of the bookmarks?

**Comment by pstein** [comment] 2022-01-04 10:32
I don't want reveal lots of private bookmarks.

This problem must be solvable without passing the bookmark file.

BO waits for exactly 2 bookmarks here. 
Surprisingly I let the Firefox open over night and at the following morning these bookmarks were resolved.
Unfortunately I don't know which 2 bookmarks had a problem.

BO should provide an overall timer which aborts ALL open bookmark searches.
This seems to be not the case. Maybe BO only waits for server responses but not for "special bookmarks" with special chars.
or overlong bookmark description or Internet connection cut or whatever.

BO timer should work as long as Firefox is running.

Could you verify this?

Can I enable textual logging?
This may eventually help.

**Comment by cadeyrn** [comment] 2022-01-04 10:56
> This problem must be solvable without passing the bookmark file.

Unfortunately I don't see an easy way to solve something that I can't reproduce. If you don't want to share all your bookmarks an idea would be to create a new profile, import your bookmarks, check the bookmarks with the add-on, remove half of the bookmarks, check again and so on until there is only a subset of bookmarks that is still affected. Maybe you see something suspicious then or are able to share a subset.

> BO should provide an overall timer which aborts ALL open bookmark searches.

As I said every request already has its own timer. So there is no point in an "overall timer" and it's not possible anyway. To abort a request the add-on has to know the problematic request. It's not possible to simply "abort everything".

The timer is set to 15 seconds per request.

> Maybe BO only waits for server responses but not for "special bookmarks" with special chars.
or overlong bookmark description or Internet connection cut or whatever.

Yes, there must be a reason if the timer does not work as expected. And we have to find that reason. I will test a few things soon but I can't promise to find something without knowing a bookmark that could cause this.

> Can I enable textual logging?

In the add-on's settings you can enable a debug output. But I don't know how useful it will be.

**Comment by Illegal-Services** [comment] 2022-02-11 11:14
Hello, I have the EXACT same problem than @pstein [pstein](https://github.com/pstein) have.

I have 2004/2006 with 39 detections recongnised as errors.

Please, get this bug to be fixed... It is very annoying.

Also, sometimes it works and end the scan, and sometimes it doesn't works and loop for infinite...

**Comment by cadeyrn** [comment] 2022-02-11 11:20
> Please fix this bug... It's very annoying.

Please provide a test case. As I already said to the issue opener: I can't fix anything without being able to reproduce the problem.

**Comment by Illegal-Services** [comment] 2022-02-11 11:24
I can't reproduce it on demand, like I said it happens randomly :/

**Comment by orbanbalage** [comment] 2022-10-01 20:49
I have the same issue, the progress was very steady and fast, but now I'm stuck for an hour or so.

```
Number of bookmarks: 28987
Checked: 28954
```

While the bookmarks were still being processed, I was monitoring the connections via. `nettop`.

Now there are 10 processes in "Established" state there.

There are 6 active processes in `about:networking#http`.

Don't know if it makes sense to compare these.

Perhaps the issue is with adding new bookmarks while the organizer is running, and that throws off the list of bookmarks to be processed and then it never completes?

I will restart the process and leave it running in the night and see what happens.

**Comment by orbanbalage** [comment] 2022-10-02 09:52
I did a duplicate clean with [bookmarks-clean-up](https://addons.mozilla.org/firefox/addon/bookmarks-clean-up/) first – and left bookmarks-organizer to run overnight. It is complete, but I don't know how long it took.

It is awesome that the bookmarks-organizer applied all redirects with a push of a button!!!

@pstein you can abort the process by disabling the Extension.

Oddly enough I tried to run a check for duplicates and it got stuck half-way. I disabled and re-enabled the extension and then ran it again without problems. Perhaps it is not an issue with specific bookmarks, but something else.

**Comment by Illegal-Services** [comment] 2022-10-28 21:30
Like @orbanbalage mentioned:
> "Perhaps the issue is with adding new bookmarks while the organizer is running, and that throws off the list of bookmarks to be processed and then it never completes?"

I think that's one of the way to create that problem.

**Comment by Illegal-Services** [comment] 2022-10-28 21:32
I probably said randomly earlier cause I was not aware of that fact.
Now I've been still using this extension, without touching my bookmarks at all (afk browser) and it works fine now.
Imo it's worth an action from the developer

**Comment by cadeyrn** [comment] 2023-01-08 21:52
> Perhaps the issue is with adding new bookmarks while the organizer is running, and that throws off the list of bookmarks to be processed and then it never completes?

This was definitively an issue and was fixed in Bookmarks Organizer 4.0. It will be release within the next few days. Since I am not aware of other causes I'll close this issue as duplicate of #112. Please open a new issue if you still can reproduce with Bookmarks Organizer 4.0.

**Closed by cadeyrn** 2023-01-08 21:52 UTC
Labels: enhancement, investigation, help needed
