### ISSUE TITLE
huge memory usage with any bookmark edit

### ISSUE THREAD

**Issue by rezad1393** [cadeyrn/bookmarks-organizer#209] opened 2023-03-17 17:11 UTC
**Describe the bug**
when this addon is enabled and I try to import bookmarks, then memory usage goes to all the RAM in system and system crashes.
when I disable this addon this behavior doesn't happen.

with this addon enabled,any pasting of bookmarks gets very slow and if I paste a lot of bookmark firefox gets very slow and bookmarks get added one bye one slowly.

this from addon usually gives errors in firefox log.
js/core/background.js

it seems that this addon monitors all the bookmarks operation and does stuff with it that can lead to crash of firefox.

**Comment by cadeyrn** [comment] 2023-03-18 19:08
Hello,

> this from addon usually gives errors in firefox log.

what exactly can be read in the log?

**Comment by rezad1393** [comment] 2023-03-19 22:26
> Hello,
> 
> > this from addon usually gives errors in firefox log.
> 
> what exactly can be read in the log?

I dont remember. and I disabled this addon so I can use firefox normally.
for example I had your addon for duplicate finder. so I disabled this addon: https://github.com/vaeth/bookmarkdupes/

but when I didnt suspect your addon and enabled this addon to remove some dups , the deletion goes very slowly.
when I disable your addon the deletion goes very fast.


I dont know if this errors are at all important and I think your addon somehow locks(?) or monitors all bookmark operation and that causes all the delays and memory leak that I saw.
```
01:50:59.671 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    initBookmarkCount moz-extension://e726126a-027e-4fce-b539-38713cfbc4a6/js/core/background.js:452
background.js:452:21

```

maybe for test you can create a firefox profile and copy many bookmarks with a lot of dups in them  to it (you can just copy paste). then install both these addons (yours and the other one) and try to remove the bookmarks with the other addon with you addo enabled and see the slow process and see it go fast when your addon is disabled.

**Comment by cadeyrn** [comment] 2023-08-13 14:38
@rezad1393 Thank you for the report and sorry for the delay. I found the cause and will try to mitigate it.

**Comment by Illegal-Services** [comment] 2023-08-13 14:42
I also noticed that problem, didn't know it was specific to this extension, cuz I have a crazy amount of extensions.
My solution when I imported a lot of bookmarks was to always simply do it in a "Private window" to avoid those problems.

**Comment by Illegal-Services** [comment] 2023-08-13 14:45
oh and btw this is totally not related to BO, but when you import a crazy amount of bookmarks, you can save an absolutely insane time and CPU x Memory load by importing without the favicons stuff. I have made a script for it to delete them and in comparaison it's mind blowing. Just clarifying this is an issue with Mozilla Firefox and not BO. And I'm talking about 7K import of bookmarks.

**Comment by rezad1393** [comment] 2023-08-13 14:57
7k??
noob.
lame
try 20k.

joking aside I had no idea private window would affect the the firefox bookmark manager window.
so if I have a normal window and a private window open and then open the bookmark manager how the hell would firefox know which state to be in.

**Comment by Illegal-Services** [comment] 2023-08-13 15:01
Well I didn't said it but I where closing all other(s) firefox profiles and windows to only remains the private one.
But the question you reminded is curious and, I'll do a few test and let you know the result

**Comment by cadeyrn** [comment] 2023-08-13 15:05
> oh and btw this is totally not related to BO, but when you import a crazy amount of bookmarks, you can save an absolutely insane time of CPU x Memory load by importing without the favicons

I believe that importing the bookmarks without favicons can make a difference. But still, there is also a cause in Bookmarks Organizer that can lead to a massive memory increase and thus a Firefox crash.

> I had no idea private window would affect the the firefox bookmark manager window.

Not directly. But extensions are disabled by default in private windows and if you didn't change this setting Bookmarks Organizer won't cause the issue as it's disabled.

**Comment by rezad1393** [comment] 2023-08-13 15:42
> Not directly. But extensions are disabled by default in private windows and if you didn't change this setting Bookmarks Organizer won't cause the issue as it's disabled.

that was not my point.

I thought addons were disabled in "firefox main windows" that you browser in and can have private and normal mode and not a special window that is bookmark manager of firefox itself.

that would mean we have a private mode that is not associated with a  window that is  but with the whole firefox itself.
I can have two window of firefox open, on in normal mode and one in private mode and then when I open bookmark manager window (the firefox one, not this addon) which one would it inherit? the last one opened maybe?

**Comment by Illegal-Services** [comment] 2023-08-13 15:45
So I've been doing a few testing on an isolated profile, copying 1000 bookmarks (right clic on bookmarks bar > paste) takes a while longer when BO is installed and active.

**Comment by cadeyrn** [comment] 2023-08-13 15:49
@rezad1393 The bookmark manager window has nothing to do with regular vs private windows at all.

**Comment by Illegal-Services** [comment] 2023-08-13 16:04
So I've been doing a few testings on an isolated profile, copying 1000 bookmarks (right clic on bookmarks bar > paste) takes a while longer (around 10 more seconds) when BO is installed and active.

with BO enabled:
20 seconds

with BO Disabled:
2 seconds

testing record video:

https://github.com/cadeyrn/bookmarks-organizer/assets/62464560/9e774705-36dd-4922-9b82-5348ab95c9e5

**Closed** 2023-08-13 16:33 UTC
Labels: bug

**Comment by rezad1393** [comment] 2023-08-13 16:57
> So I've been doing a few testings on an isolated profile, copying 1000 bookmarks (right clic on bookmarks bar > paste) takes a while longer (around 10 more seconds) when BO is installed and active.
> 
> with BO enabled: 20 seconds
> 
> with BO Disabled: 2 seconds
> 
> testing record video:
> BO_test.mp4

no need for that.
the dev have acknowledged and fixed the issue it seems.

and next time go on 10k bookmark.
1000 is rookie number :)

**Comment by Illegal-Services** [comment] 2023-08-13 17:00
> no need for that. the dev have acknowledged and fixed the issue it seems.
> 
> and next time go on 10k bookmark. 1000 is rookie number :)

I would have wait 9x longer doing so

**Comment by cadeyrn** [comment] 2023-08-17 09:35
@rezad1393 Bookmarks Organizer 4.1.0 has been released and it includes a fix for the reported issue.
