### ISSUE TITLE
Hangs on duplicates

### ISSUE THREAD

**Issue by jimcuk** [cadeyrn/bookmarks-organizer#48] opened 2017-08-14 01:09 UTC
add on hangs when processing duplicates

**Comment by JustMyGithub** [comment] 2017-09-14 11:46
When I search for duplicates, the "progress"-animation does not stop and I cannot delete one of the first 3 or 4 duplicates. Is that the problem you are talking about?!

**Comment by Jan02** [comment] 2017-09-20 16:30
happens to me too: https://gfycat.com/PoorCorruptAtlasmoth

**Comment by bunnybooboo** [comment] 2017-11-23 09:37
So this issue is actually that the icon `images/icon.svg` and its lower animated spinner/bounce icons give the impression that the task is still running, even though it's finished. Just tested in Firefox 57 and Firefox Nightly 59 and experienced this perceived "hang".

**Comment by bunnybooboo** [comment] 2017-11-23 09:49
In fact this is a duplicate of #41

**Comment by cadeyrn** [comment] 2018-02-24 11:03
Thanks for reporting. Will be fixed in Bookmarks Organizer 2.0.

**Closed** 2018-02-24 11:03 UTC

**Comment by cadeyrn** [comment] 2018-03-10 18:24
Bookmarks Organizer 2.0 has been released:
https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/

If you like it please let a positive review there. ;-)
