### ISSUE TITLE
Bad bookmark path when previous bookmarks names are empty (icon only) or specific characters in names

### ISSUE THREAD

**Issue by sfMan** [cadeyrn/bookmarks-organizer#128] opened 2019-10-12 09:47 UTC
I find this addon very useful however I found one problem in it. Its a huge bug. I don't know if its possible to fix it or its connected to firefox specific.
Add-on should take into account cases when special characters like # or / characters appear in the bookmarks name or bokmarks subfolder folder. It causes wrong location and address info.
Example: 
we have bookmar folder called "MAIN". Inside there are two subfolders named "A / B" and "C". There's bookmark SomeLink placed in C subfolder. Addon will report SomeLink location as C and it should be MAIN/C. Similar error type is caused by # character in bookmark names. I think these characters cause the add-on to mistake the path by treating it as part of the path.
I hope this will help fixing this bug. 

Update: found another element causing bad bookmark path readings - the additional bookmarks separator in menu

Update2: Another case of incorrect bookmark location information is caused by untitled bookmarks (empty string, icon only)

In each case of incorrectly entered bookmark location, the condition is that the described situations (/, empty name, etc) occur before the bookmark, the location of which is read.

**Comment by B00ze64** [comment] 2020-06-29 19:23
I just installed this, and tested finding duplicates, and PATH is badly broken (or at least does not work as expected):

**First entry shows:** Path: Bookmarks Menu / Hardware / Drivers
The duplicate shows: Software / CD|DVD / Tools _(We've lost Bookmarks Menu)_
**Second entry show:** Path: Bookmarks Menu / Hardware / RAID
The duplicate shows: Path: Reviews / Storage _(We've lost Boorkmarks Menu / Hardware)_
**Third entry shows:** Path: / _(We've lost everything)_
The duplicate shows: Path: / _(We've lost everything)_
and so on...

So PATH really isn't working as expected, makes the duplicates function mostly useless...

**Comment by Illegal-Services** [comment] 2022-02-11 18:28
I experience the same problem as @B00ze64

**Comment by cadeyrn** [comment] 2023-01-08 20:38
I was not able to reproduce. Please open a new issue if you still can reproduce in Bookmarks Organizer 4.0 that will be released within the next few days.

**Closed by cadeyrn** 2023-01-08 20:38 UTC
Labels: investigation

**Comment by Illegal-Services** [comment] 2023-01-18 23:30
Same problem happen on v4.0.0.

@cadeyrn - Can you add me on Discord, or Telegram so that I send you my bookmarks file, and you can try it out by yourself?

telegram:  https://t.me/mathieudummy
discord:    Mathieu#4291

**Comment by cadeyrn** [comment] 2023-01-19 09:27
I neither use Telegram nor Discord. But you could upload it somewhere where it get self-destroyed after a certain time or after x donwloads and send me the link via this contact form: https://www.soeren-hentzschel.at/kontakt/

**Comment by Illegal-Services** [comment] 2023-01-19 10:16
Done that!
