### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by rayman89** [cadeyrn/bookmarks-organizer#43] opened 2017-07-10 16:55 UTC
I wanted to request the ability to easily select multiple bookmarks listed to exclude.  For example clicking on a folder will give you the option to delete them or exclude them temporary or permanently. Right clicking on a bookmark or clicking on a checkbox or something like that will give you the options to exclude that domain permanently or temporarily or delete all the bookmarks from that domain (that are listed as broken or that need redirect).

**Comment by cadeyrn** [comment] 2017-07-10 19:28
Thank you for your suggestion. A whitelist is already planned, but I can't say when it will be implemented.

If someone wants to implement this feature I accept pull requests. ;)

**Comment by cadeyrn** [comment] 2018-02-26 10:29
duplicate of #11.

**Closed by cadeyrn** 2018-02-26 10:29 UTC
