### ISSUE TITLE
[enhancement]  checkbox

### ISSUE THREAD

**Issue by perdolka** [cadeyrn/bookmarks-organizer#75] opened 2018-03-10 22:17 UTC
Checkbox - to mark false positive results as permanent exception.

**Comment by cadeyrn** [comment] 2018-03-11 12:39
Thank you for your feature request. It's a duplicate of #11 and already planned for a future update. Bookmarks Organizer 2.0 with all the important under the hood changes has been released so it's possible now to focus on feature enhancements. ;-)

**Closed by cadeyrn** 2018-03-11 12:39 UTC
