### ISSUE TITLE
Deleting duplicates

### ISSUE THREAD

**Issue by CristianEmanuel** [cadeyrn/bookmarks-organizer#84] opened 2018-05-13 05:28 UTC
Hello. I have more than 900 bookmarks duplicates (importing from Firefox to Chrome and to browsers from saved bookmarks done that), no option/button to delete them all at once. Is there a option to delete them all fast?
Thank you.

**Comment by cadeyrn** [comment] 2018-05-13 06:42
Not yet. It's a duplicate of #8.

**Closed by cadeyrn** 2018-05-13 06:42 UTC

**Comment by Thomas-D-C** [comment] 2024-02-27 23:24
> It's a duplicate of #8.

Do you mean #38 ?
Or maybe #53 ?

**Comment by cadeyrn** [comment] 2024-02-28 07:25
Issue #8 is about seleting and deleting multiple bookmarks at once. You can also see this as a duplicate of #38 or as a subset of #53.
