### ISSUE TITLE
Check for broken links is reporting false positives depending on Firefox settings

### ISSUE THREAD

**Issue by gitflo** [cadeyrn/bookmarks-organizer#111] opened 2019-02-26 10:11 UTC
Hi all,

I'm opening this ticket on addon version 3.1.0. However, the behaviour seems to have been mentioned in the addon's rating comments before already many times, see e.g. [1]-[4] for a small choice. This ticket seems to be somehow related to #77 and might also be related to issue #59.

**Description of the issue**

The check for broken links is reporting many links as "red" (error) while they are perfectly working. Looking at the details, to me it looked strange that this seemed to be related to complete sites. In my example, all links to YouTube as well as to Microsoft had been reported.

**Root cause**

Digging deeper and checking the browser console revealed the root cause:

```
Die Ressource auf "https://www.youtube.com/watch?v=(...)" wurde blockiert, weil das Blockieren von Seitenelementen aktiviert ist.[Weitere Informationen]
Die Ressource auf "https://www.youtube.com/watch?v=(...)" wurde blockiert, weil das Blockieren von Seitenelementen aktiviert ist.[Weitere Informationen]
Die Ressource auf "https://docs.microsoft.com/en-us/windows-hardware/drivers/what-s-new-in-driver-development#windows-driver-frameworks-wdf" wurde blockiert, weil das Blockieren von Seitenelementen aktiviert ist.[Weitere Informationen]
```

**Solution**

I had the tracking protection activated for all windows. Reducing it to "only private windows" fixed the behaviour, i.e. the abovementioned links weren't reported as broken anymore.

From user point of view this is clearly a bug. If it turns out that it can't be fixed, e.g. due to API limitations, the user would at least expect a clear warning.

Best regards
 Florian

[1] https://addons.mozilla.org/de/firefox/addon/bookmarks-organizer/reviews/1221005/
[2] https://addons.mozilla.org/de/firefox/addon/bookmarks-organizer/reviews/1187053/
[3] https://addons.mozilla.org/de/firefox/addon/bookmarks-organizer/reviews/1068880/
[4] https://addons.mozilla.org/de/firefox/addon/bookmarks-organizer/reviews/982030/

**Comment by cadeyrn** [comment] 2019-02-26 10:18
Hi,

thanks for the report. It's a duplicate of #77 and #109. In #109 I explained the two options:
https://github.com/cadeyrn/bookmarks-organizer/issues/109#issuecomment-460963104

One of these two option will be implemented with the next update.

**Comment by cadeyrn** [comment] 2023-01-07 22:20
Closing as duplicate (see comment from 2019, I forgot to close the issue).

**Closed by cadeyrn** 2023-01-07 22:20 UTC
Labels: duplicate
