### ISSUE TITLE
Duplicate check don't stop.

### ISSUE THREAD

**Issue by array** [cadeyrn/bookmarks-organizer#60] opened 2017-11-12 22:40 UTC
In Firefox 57 beta(already release),Duplicate check Bookmarks doesn't end.
In JA Location.

Firefox57 BetaはほとんどReleaseですが、Duplicate Checkが終わりません。日本語環境です。

**Comment by cadeyrn** [comment] 2017-11-13 10:24
Thank you for reporting the issue. Do you have more information? A never ending check for broken bookmarks makes sense because there is no timeout (will be implemented soon), but I never had problems with the check for duplicates. Maybe you could export your bookmarks and attach the file?

**Comment by array** [comment] 2017-11-15 07:27
OK、I attached my bookmarks.
[bookmarks.zip](https://github.com/cadeyrn/bookmarks-organizer/files/1473712/bookmarks.zip)

**Comment by unabatedshagie** [comment] 2017-11-22 20:22
Just to add that I'm also having problems with this.

**Comment by bunnybooboo** [comment] 2017-11-23 09:46
Duplicate issue of #48

**Comment by Gitoffthelawn** [comment] 2017-11-23 19:35
After testing 99% of the bookmarks successfully in rapid fashion, it can take 15-30 minutes for 'Checked' to equal 'Number of bookmarks' for the last several bookmarks.  I don't think this is just a logo issue.

**Comment by unabatedshagie** [comment] 2017-11-24 09:07
The only problem with that is if you only have a few duplicates you're unable to click on the edit/delete links as the spinner must be on top which is why I didn't think it was working as I didn't scroll down slightly to get to some bookmarks that were below the spinner.

I did find a workaround though, if you make your window/tab narrow vertically, you can scroll the page and access the edit/delete buttons on all the bookmarks.

**Comment by bunnybooboo** [comment] 2017-11-25 12:16
Those unclickable items appear to be bookmark separators. See: #61

**Comment by cadeyrn** [comment] 2018-02-24 11:04
It's a duplicate of #48 and will be fixed in Bookmarks Organizer 2.0. Thanks for reporting.

**Closed by cadeyrn** 2018-02-24 11:04 UTC
Labels: duplicate
